name: Node.js CI

on:
  push:
    branches: [ main, actions ]
    paths: [ "src/**", "tests/**", ".github/**" ]
    
  pull_request:
    branches: [ main ]
    paths: [ "src/**", "tests/**" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    
    - run: npm run update
